name: update_emails

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  update_emails:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          curl https://stat.ethz.ch/pipermail/r-devel/ | head -n 50 | sed -n 's/.*href="\([^"]*txt.gz\).*/\1/p' | xargs -I % sh -c 'wget https://stat.ethz.ch/pipermail/r-devel/%; gunzip -f %'
          git commit -am "Update emails" && git push
